### ISSUE TITLE
Tests failing in createWithSwedishDateLocaleTomlProducesSwedishDate

### ISSUE THREAD

**Issue by pascalrobert** [gustavkarlsson/rocketchat-jira-trigger#38]
Hi,

I'm trying to build our own version of your tool, to add a compact mode (only title and link of the issue). But two tests fails:

`org.junit.ComparisonFailure: expected:<"[to]"> but was:<"[on]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at se.gustavkarlsson.rocketchat.jira_trigger.configuration.MessageConfigurationTest.createWithSwedishDateLocaleTomlProducesSwedishDate(MessageConfigurationTest.java:85)`

`org.junit.ComparisonFailure: expected:<"[Thu]"> but was:<"[Wed]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at se.gustavkarlsson.rocketchat.jira_trigger.configuration.MessageConfigurationTest.createWithUsEnglishDateLocaleTomlProducesSwedishDate(MessageConfigurationTest.java:94)`

**Comment by gustavkarlsson** [comment]
Thanks for reporting this. It's quite obviously a timezone issue. What timezone are you in?

**Comment by pascalrobert** [comment]
America/Toronto

**Comment by gustavkarlsson** [comment]
So, the bug has been fixed in release 1.1.0, but I believe what you are looking for is already supported.

You can set your configuration to something like:
```
[message]
default_fields = []
extended_fields = ["assignee", "status", "reporter", "priority"]
```

This will not show any of the fields by default and only if you append a **+** (ex: ABC-123+), it will show the extended fields.

**Comment by pascalrobert** [comment]
In fact, we want 3 modes, compact (title and link), default and extended, hence the changes to the source. But it's Git, so I can merge your changes with our local ones :-)

**Comment by gustavkarlsson** [comment]
Of course! Just go ahead :)
