### ISSUE TITLE
Unable to white list users, channels

### ISSUE THREAD

**Issue by TomaszDom** [gustavkarlsson/rocketchat-jira-trigger#43]
I'm using rocketchat server 0.58.2 (from tar package) with LDAP authentication, when I configure the trigger to whitelist users it blacklists every user, same behaviour with channels.

Let's say I add this to my config.toml file:

```
[rocketchat]
whitelisted_users = [ "tomaszd" ]
```
Nobody can use the trigger now, not even user `tomaszd`:

`s.g.r.j.routes.DetectIssueRoute - Forbidden user encountered. ID: ID_HERE, Name: tomaszd. Ignoring`

Same story with channels. The only way to make it work is not have any values in any whitelists.

**Comment by TomaszDom** [comment]
I've just tested this without LDAP on a clean install and the same thing happens, adding anyone to the whitelist in practice disables the trigger completely, messages from people on the whitelist are ignored.

**Comment by TomaszDom** [comment]
Are you planning on fixing this?

**Comment by gustavkarlsson** [comment]
Yes, of course. I've just been busy. This is at the top of my list for this project.

**Comment by gustavkarlsson** [comment]
Check out [Release 1.2.2](https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases/tag/1.2.2)

**Comment by TomaszDom** [comment]
I was able to start the process once, when I stopped it to configure the whitelist, I can't start it again (even with the most basic config only with login and password):

```
2017-10-25 18:19:48,987 [main] INFO  s.g.r.j.RestClientProvider - Using basic authentication
2017-10-25 18:19:48,992 [main] INFO  s.g.r.j.RestClientProvider - Password provided through configuration
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
        at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
        at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
        at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<init>(ManagedNHttpClientConnectionFactory.java:75)
        at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<init>(ManagedNHttpClientConnectionFactory.java:83)
        at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<clinit>(ManagedNHttpClientConnectionFactory.java:64)
        at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.<init>(ApacheAsyncHttpClient.java:175)
        at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.<init>(ApacheAsyncHttpClient.java:123)
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.doCreate(DefaultHttpClientFactory.java:68)
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.create(DefaultHttpClientFactory.java:35)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:63)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35)
        at se.gustavkarlsson.rocketchat.jira_trigger.RestClientProvider.get(RestClientProvider.java:32)
        at se.gustavkarlsson.rocketchat.jira_trigger.Server.<init>(Server.java:48)
        at se.gustavkarlsson.rocketchat.jira_trigger.App.<init>(App.java:19)
        at se.gustavkarlsson.rocketchat.jira_trigger.App.main(App.java:26)
```

**Comment by gustavkarlsson** [comment]
Very strange, but this is clearly a bug in a third party library, and not related to the original bug.

**Comment by gustavkarlsson** [comment]
Actually, it's probably NOT a bug in a library.
I've opened #45 to resolve it.

**Comment by TomaszDom** [comment]
Works now, thanks!
