### ISSUE TITLE
Unable to build - getting 401 Unauthorized error on httpclient plugin on atlassian mavenlink

### ISSUE THREAD

**Issue by pathikb** [gustavkarlsson/rocketchat-jira-trigger#44]
When I try to build using the instructions given, I get the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not determine artifacts for com.atlassian.httpclient:atlassian-httpclient-plugin:0.23.0
   > Could not get resource 'https://maven.atlassian.com/repository/public/com/atlassian/httpclient/atlassian-httpclient-plugin/0.23.0/atlassian-httpclient-plugin-0.23.0.atlassian-plugin'.
      > Could not HEAD 'https://maven.atlassian.com/repository/public/com/atlassian/httpclient/atlassian-httpclient-plugin/0.23.0/atlassian-httpclient-plugin-0.23.0.atlassian-plugin'. Received status code 401 from server: Unauthorized

Please suggest a way to fix this

**Comment by gustavkarlsson** [comment]
Thank you for reporting this. Hoping to it this week. 
This failed Travis build also confirms it: https://travis-ci.org/gustavkarlsson/rocketchat-jira-trigger/jobs/270170094

Reason seems to be that the Atlassian Maven repository now requires authentication.

**Comment by pathikb** [comment]
If you could point me in the right direction, it would really help me try and fix this issue myself.

**Comment by gustavkarlsson** [comment]
Fixed in [Release 1.2.1](https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases/tag/1.2.1)

**Comment by pathikb** [comment]
Well, the build issue is resolved but now I get the below error when I try to run the binary -

root@vps2:~/rocketchat-jira-trigger/build/install/rocketchat-jira-trigger# ./bin/rocketchat-jira-trigger config.tml 
2017-10-26 16:12:45,658 [main] INFO  s.g.r.j.RestClientProvider - Using basic authentication
2017-10-26 16:12:45,660 [main] INFO  s.g.r.j.RestClientProvider - Password provided through configuration
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<init>(ManagedNHttpClientConnectionFactory.java:75)
	at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<init>(ManagedNHttpClientConnectionFactory.java:83)
	at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<clinit>(ManagedNHttpClientConnectionFactory.java:64)
	at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.<init>(ApacheAsyncHttpClient.java:175)
	at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.<init>(ApacheAsyncHttpClient.java:123)
	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.doCreate(DefaultHttpClientFactory.java:68)
	at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.create(DefaultHttpClientFactory.java:35)
	at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:63)
	at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35)
	at se.gustavkarlsson.rocketchat.jira_trigger.RestClientProvider.get(RestClientProvider.java:32)
	at se.gustavkarlsson.rocketchat.jira_trigger.Server.<init>(Server.java:48)
	at se.gustavkarlsson.rocketchat.jira_trigger.App.<init>(App.java:19)
	at se.gustavkarlsson.rocketchat.jira_trigger.App.main(App.java:26)

**Comment by gustavkarlsson** [comment]
You are right. Somehow the fix introduced another bug that I did not detect. I will create a new issue for it.

Sorry for the trouble!
