### ISSUE TITLE
Unable to connect to JIRA instance (7.5.0, Windows Server 2008 R2, IIS 7.5 proxy/https)

### ISSUE THREAD

**Issue by TomaszDom** [gustavkarlsson/rocketchat-jira-trigger#46]
This trigger now works great with one of my JIRA instances (7.3.4 running on Ubuntu, natively on its own Tomcat instance with https enabled).

It can't connect to my other instance (7.5.0 running on Windows Server 2008 R2, behind IIS 7.5 webserver as proxy with https enabled).

Also, the trigger instance keeps running despite not being connected to anything...?

Unfortunately the logs are not very informative (null?):

```
2017-10-26 21:30:40,995 [main] INFO  s.g.r.j.RestClientProvider - Using basic authentication
2017-10-26 21:30:40,999 [main] INFO  s.g.r.j.RestClientProvider - Password provided through configuration
2017-10-26 21:30:46,528 [main] WARN  s.g.rocketchat.jira_trigger.Server - Failed to connect to JIRA
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.ConnectException
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:289)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:111)
        at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
        at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.get(DelegatingPromise.java:102)
        at se.gustavkarlsson.rocketchat.jira_trigger.Server.logJiraServerInfo(Server.java:68)
        at se.gustavkarlsson.rocketchat.jira_trigger.App.<init>(App.java:20)
        at se.gustavkarlsson.rocketchat.jira_trigger.App.main(App.java:26)
Caused by: java.lang.RuntimeException: java.net.ConnectException
        at com.google.common.base.Throwables.propagate(Throwables.java:156)
        at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient$6.apply(ApacheAsyncHttpClient.java:404)
        at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient$6.apply(ApacheAsyncHttpClient.java:398)
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:305)
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:302)
        at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:208)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:977)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:188)
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$2.run(SettableFuturePromiseHttpPromiseAsyncClient.java:59)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: null
        at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:170)
        at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:560)
        at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:821)
        at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:182)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:212)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:157)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:350)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:191)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        ... 1 common frames omitted
2017-10-26 21:30:46,528 [main] INFO  s.g.rocketchat.jira_trigger.Server - Starting server...
2017-10-26 21:30:46,593 [Thread-1] INFO  org.eclipse.jetty.util.log - Logging initialized @6159ms to org.eclipse.jetty.util.log.Slf4jLog
2017-10-26 21:30:46,642 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - == Spark has ignited ...
2017-10-26 21:30:46,642 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:4568
2017-10-26 21:30:46,645 [Thread-1] INFO  org.eclipse.jetty.server.Server - jetty-9.4.4.v20170414
2017-10-26 21:30:46,672 [Thread-1] INFO  org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0
2017-10-26 21:30:46,673 [Thread-1] INFO  org.eclipse.jetty.server.session - No SessionScavenger set, using defaults
2017-10-26 21:30:46,675 [Thread-1] INFO  org.eclipse.jetty.server.session - Scavenging every 600000ms
2017-10-26 21:30:46,689 [Thread-1] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@22a390ed{HTTP/1.1,[http/1.1]}{0.0.0.0:4568}
2017-10-26 21:30:46,690 [Thread-1] INFO  org.eclipse.jetty.server.Server - Started @6257ms
```
My toml config is copy-pasted from the working JIRA instance with the port, URL and login/pass changed, so there is no port collision and the user and password is definitely correct (copy pasted it from the config into JIRA to check). Any ideas?

**Comment by TomaszDom** [comment]
Hint: It could be a cipher mismatch, as this server doesn't work with TLS higher than 1.0 for example, but it may be a red herring.

**Comment by gustavkarlsson** [comment]
Can you make a manual request to the [JIRA REST API](https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis)?

**Comment by gustavkarlsson** [comment]
Btw, the reason it still keeps running is this: The first (failed) connection attempt is only used to check and print the JIRA server name and version. It does not prevent future connection attempts.

**Comment by gustavkarlsson** [comment]
@TomaszDom have you tried making a manual request (like I suggested above) to ensure that it's not a networking problem?
