### ISSUE TITLE
Docker: Insufficient threads

### ISSUE THREAD

**Issue by reda-alaoui** [gustavkarlsson/rocketchat-jira-trigger#48]
Hello,

I have the following error with docker container 1.2.3:

```
2018-01-27 13:29:40,685 [main] INFO  s.g.rocketchat.jira_trigger.Server - Starting server...                                                     
rocketchat-jira-trigger_1  | 2018-01-27 13:29:40,778 [Thread-1] INFO  org.eclipse.jetty.util.log - Logging initialized @2495ms to org.eclipse.jetty.util.log.Slf4jLog         
rocketchat-jira-trigger_1  | 2018-01-27 13:29:40,835 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - == Spark has ignited ...                                                
rocketchat-jira-trigger_1  | 2018-01-27 13:29:40,835 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:4567                                            
rocketchat-jira-trigger_1  | 2018-01-27 13:29:40,839 [Thread-1] INFO  org.eclipse.jetty.server.Server - jetty-9.4.4.v20170414                                                 
rocketchat-jira-trigger_1  | 2018-01-27 13:29:40,853 [Thread-1] ERROR spark.Spark - ignite failed                                                                             
rocketchat-jira-trigger_1  | java.lang.IllegalStateException: Insufficient threads: max=10 < needed(acceptors=4 + selectors=8 + request=1)                                    
rocketchat-jira-trigger_1  |    at org.eclipse.jetty.server.Server.doStart(Server.java:414)                                                                                   
rocketchat-jira-trigger_1  |    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)                                                        
rocketchat-jira-trigger_1  |    at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:130)                                                        
rocketchat-jira-trigger_1  |    at spark.Service.lambda$init$2(Service.java:504)                                                                                              
rocketchat-jira-trigger_1  |    at java.lang.Thread.run(Thread.java:748)
```

Using docker container 1.2.0 solves the issue.

**Comment by gustavkarlsson** [comment]
Looks like the max_threads setting is too log. I'd suggest setting it to `30` and see if that helps

**Comment by gustavkarlsson** [comment]
FYI, I'm increasing the default for next release.

**Comment by gustavkarlsson** [comment]
Fixed. Check [releases](https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases)

**Comment by reda-alaoui** [comment]
Thank you :)
