### ISSUE TITLE
logs are too verbose for a 404 response to outgoing webhook

### ISSUE THREAD

**Issue by art-shutter** [gustavkarlsson/rocketchat-jira-trigger#74]
My logs are overflowing from output jira trigger generates. I believe this needs to be fixed. Here's the example:
```
I20191220-13:25:26.095(3) server.js:204 Integrations ➔ Outgoing WebHook.error Error for the Integration "jira" to http://172.17.0.1:4567/ is: 
I20191220-13:25:26.096(3) server.js:204 Integrations ➔ Outgoing WebHook.error { Error: failed [404] <html><body><h2>404 Not found</h2></body></html>     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:139:11)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)   response:     { statusCode: 404,      content: '<html><body><h2>404 Not found</h2></body></html>',      headers:        { connection: 'close',         date: 'Fri, 20 Dec 2019 10:25:26 GMT',         'content-type': 'text/html;charset=utf-8',         server: 'Jetty(9.4.4.v20170414)' },      data: null } } 
```

**Comment by gustavkarlsson** [comment]
It sounds to me like it's not set up correctly. Is the integration even working? A `404` response should indicate that you're targeting the wrong endpoint or not using the `application/json` content type...
